name: Automerge Release PR

  on:
    pull_request:

    check_suite:
      types:
        - completed

jobs:

  autoapprove:
    runs-on: ubuntu-latest
    if: github.actor == 'monetaur-bot'
    steps:
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  automerge:
    needs: [autoapprove]
    runs-on: ubuntu-latest
    if: github.actor == 'monetaur-bot'
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_LOGIN: monetaur-bot
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
